
debug: false

# Spring Configuration

local.server.port: 7777

logging:
    level:
        org:
            springframework:
                data:
                    r2dbc: info
spring:

    #test || dev || prod
    #traveltime && parking
    #httpretrieval || fileretrieval

    profiles:
        include: postgres, traveltime, dev, http

    h2:
        console:
            enabled: on
    main:
        lazy-initialization: on

    application:
        name: OpenCity

    jpa:
        open-in-view: on
        show-sql: off
        generate-ddl: off

        hibernate:
            ddl-auto: none

    banner:
        image:
            invert: on
    output:
        ansi:
            enabled: always

    rsocket:
        server:
            mapping-path: /traveltimesocket
            transport: websocket
            port: 9897

# Traffic Data Configuration

# Eigenaar dataset: Gemeente Amsterdam, Verkeer en Openbare Ruimte ---
parking:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/ParkingLocation.json
    initialdelay: 0s
    requestinterval: 60s
    elementdelay: 0s


guidancesign:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/GuidanceSign.json
    initialdelay: 0s
    requestinterval: 60s
    elementdelay: 0s

traveltime:
    #dataset webpage: https://data.amsterdam.nl/datasets/KDrDITPUOgY4wQ/
    url: http://web.redant.net/~amsterdam/ndw/data/reistijdenAmsterdam.geojson
    initialdelay: 5s
    requestinterval: 20s
    elementdelay: 0s
    dbEnabled: true


    
#    -- traveltime properties --
#    Timestamp:    Timestamp van het moment waarop de reistijd bepaalt is
#    Velocity:    Huidige snelheid (km/u) op traject
#    Length:      Lengte van traject (in meters)
#    Traveltime:  De huidige reistijd op het traject
#
#    -- geometry --
#    coordinates:    De coördinaten van het traject, in Rijksdriehoekscoördinaten en in de volgorde van de rijrichting

#-----------------------

# https://opendata.rdw.nl/Parkeren/Open-Data-Parkeren-Index-Statisch-en-Dynamisch/f6v7-gjpa
