debug:  true

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: debug

  path: /home/stormraptor/log

# Traffic Data Configuration

parking:
  url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/ParkingLocation.json
  initialdelay: 0s
  requestinterval: 60s
  elementdelay: 0s

guidancesign:
  url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/GuidanceSign.json
  initialdelay: 0s
  requestinterval: 600ms
  elementdelay: 0ms
  saveToDbEnabled: true

traveltime:
  #dataset webpage: https://data.amsterdam.nl/datasets/KDrDITPUOgY4wQ/
  url: http://web.redant.net/~amsterdam/ndw/data/reistijdenAmsterdam.geojson
  initialdelay: 0s
#  requestinterval: 3072ms
#  elementdelay: 3ms

  requestinterval: 0ms
  elementdelay: 0ms

  saveToDbEnabled: true

#local.server.port: 7777
spring:

  # dev || prod
  #traveltime && parking && guidancesign
  #http || file
  profiles:
    include: dev, postgres, guidancesign, file
  rsocket:
    server:
      mapping-path: /traveltimesocket
      transport: websocket
      port: 9897
  h2:
    console:
    enabled: on
  main:
    lazy-initialization: on

  application:
    name: OpenCity

  jpa:
    open-in-view: on
    show-sql: off
    generate-ddl: off

  hibernate:
    ddl-auto: off

  banner:
    image:
      invert: on

  output:
    ansi:
      enabled: always

---
spring:
  profiles: "!test"

fileadapter:
  folder: /trafficdata/new/guidancesign

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  database: test_db

#postgres:
#  host: 192.168.178.45
#  port: 5432
#  user: pi
#  password: S99ncezg
#  database: trafficdata

---
spring:
  profiles: test

fileadapter:
  testfolder: /traveltimedata/traveltimesmall/

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: admin
  database: travel_time_small
---

#    -- Traveltime informatie van de data provider:

#   taken from:  https://opendata.rdw.nl/Parkeren/Open-Data-Parkeren-Index-Statisch-en-Dynamisch/f6v7-gjpa
#
#    Timestamp:   Timestamp van het moment waarop de reistijd is berekend
#    Velocity:    Huidige snelheid (km/u) op traject
#    Length:      Lengte van traject (in meters)
#    Traveltime:  De huidige reistijd op het traject
#
#    -- geometry --
#    coordinates:    De coördinaten van het traject, in Rijksdriehoekscoördinaten en in de volgorde van de rijrichting

#-----------------------

