debug: false

# Spring Configuration

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/trafficdata
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: true
        show-sql: false
        generate-ddl: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                jdbc:
                    lob:
                       non_contextual_creation: true
    banner:
        image:
            invert: true

#  Embedded server configuration

server:
    port: 9090

# Traffic Data Configuration


# Eigenaar: Gemeente Amsterdam, Verkeer en Openbare Ruimte ---
parking:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/ParkingLocation.json
    initialdelay: 0
    requestinterval: 60

guidancesign:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/GuidanceSign.json
    initialdelay: 0
    requestinterval: 60

traveltime:
    #dataset webpage: https://data.amsterdam.nl/datasets/KDrDITPUOgY4wQ/
    url: http://web.redant.net/~amsterdam/ndw/data/reistijdenAmsterdam.geojson
    initialdelay: 0
    requestinterval: 5
#-----------------------

