debug: false


# Spring Configuration

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/trafficdata
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: true
        show-sql: false
        generate-ddl: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                jdbc:
                    lob:
                       non_contextual_creation: true
    banner:
        image:
            invert: true

    profiles:
        include: traveltime

#  Embedded server configuration

server:
    port: 9090

# Traffic Data Configuration


# Eigenaar dataset: Gemeente Amsterdam, Verkeer en Openbare Ruimte ---
parking:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/ParkingLocation.json
    initialdelay: 0
    requestinterval: 1000

guidancesign:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/GuidanceSign.json
    initialdelay: 0
    requestinterval: 1000

traveltime:
    #dataset webpage: https://data.amsterdam.nl/datasets/KDrDITPUOgY4wQ/
    url: http://web.redant.net/~amsterdam/ndw/data/reistijdenAmsterdam.geojson
    initialdelay: 0
    requestinterval: 1000
    
#    -- traveltime properties --
#    Timestamp:    Timestamp van het moment waarop de reistijd bepaalt is
#    Velocity:    Huidige snelheid (km/u) op traject
#    Length:      Lengte van traject (in meters)
#    Traveltime:  De huidige reistijd op het traject
#
#    -- geometry --
#    coordinates:    De coördinaten van het traject, in Rijksdriehoekscoördinaten en in de volgorde van de rijrichting

#-----------------------

# https://opendata.rdw.nl/Parkeren/Open-Data-Parkeren-Index-Statisch-en-Dynamisch/f6v7-gjpa
