
debug: false

# Spring Configuration

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/logdb?autoReconnect=false&serverTimezone=Europe/Amsterdam
        username: root
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        open-in-view: true
        show-sql: true
        generate-ddl: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    banner:
        image:
            invert: true
            
            
#  Embedded server configuration

server:
    port: 9090


# Traffic Data Configuration

parking:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/ParkingLocation.json
    initialdelay: 0
    requestinterval: 60

guidancesign:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/GuidanceSign.json
    initialdelay: 0
    requestinterval: 60