debug: false

# Spring Configuration

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/trafficdata
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        open-in-view: true
        show-sql: false
        generate-ddl: true
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                jdbc:
                    lob:
                       non_contextual_creation: true
    banner:
        image:
            invert: true

#  Embedded server configuration

server:
    port: 9090

# Traffic Data Configuration

parking:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/ParkingLocation.json
    initialdelay: 0
    requestinterval: 60

guidancesign:
    url: http://opd.it-t.nl/Data/parkingdata/v1/amsterdam/GuidanceSign.json
    initialdelay: 0
    requestinterval: 60
#
#        52.37063538130748, 4.899999460629829*
#        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB6SSvjmmzWA9zOVHhh4IsBbp3qqY25qas&callback=initMap">
